openapi: 3.0.1
info:
  title: Get Asset List
  version: 1.0.0
  description: Gets a list of all assets and endpoints
servers:
  - url: https://argosecure.com/
paths:
  /api/globalassets/{tenantId}:
    get:
      operationId: GetAssetList
      summary: get a list of all assets and endpoints
      parameters:
          - in: path
            name: tenantId
            schema:
                type: string
            required: true
            description: The Tenant ID to provide for the API call.
